/*
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.namsor.sdk2.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.namsor.sdk2.model.APIBillingPeriodUsageOut;
import com.namsor.sdk2.model.APIPlanSubscriptionOut;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.namsor.sdk2.invoke.JSON;

/**
 * APIPeriodUsageOut
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-28T10:15:07.323+01:00[Europe/Berlin]")
public class APIPeriodUsageOut {
  public static final String SERIALIZED_NAME_SUBSCRIPTION = "subscription";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION)
  private APIPlanSubscriptionOut subscription;

  public static final String SERIALIZED_NAME_BILLING_PERIOD = "billingPeriod";
  @SerializedName(SERIALIZED_NAME_BILLING_PERIOD)
  private APIBillingPeriodUsageOut billingPeriod;

  public static final String SERIALIZED_NAME_OVERAGE_EXCL_TAX = "overageExclTax";
  @SerializedName(SERIALIZED_NAME_OVERAGE_EXCL_TAX)
  private Double overageExclTax;

  public static final String SERIALIZED_NAME_OVERAGE_INCL_TAX = "overageInclTax";
  @SerializedName(SERIALIZED_NAME_OVERAGE_INCL_TAX)
  private Double overageInclTax;

  public static final String SERIALIZED_NAME_OVERAGE_CURRENCY = "overageCurrency";
  @SerializedName(SERIALIZED_NAME_OVERAGE_CURRENCY)
  private String overageCurrency;

  public static final String SERIALIZED_NAME_OVERAGE_QUANTITY = "overageQuantity";
  @SerializedName(SERIALIZED_NAME_OVERAGE_QUANTITY)
  private Long overageQuantity;

  public APIPeriodUsageOut() {
  }

  public APIPeriodUsageOut subscription(APIPlanSubscriptionOut subscription) {
    
    this.subscription = subscription;
    return this;
  }

   /**
   * Get subscription
   * @return subscription
  **/
  @javax.annotation.Nullable
  public APIPlanSubscriptionOut getSubscription() {
    return subscription;
  }


  public void setSubscription(APIPlanSubscriptionOut subscription) {
    this.subscription = subscription;
  }


  public APIPeriodUsageOut billingPeriod(APIBillingPeriodUsageOut billingPeriod) {
    
    this.billingPeriod = billingPeriod;
    return this;
  }

   /**
   * Get billingPeriod
   * @return billingPeriod
  **/
  @javax.annotation.Nullable
  public APIBillingPeriodUsageOut getBillingPeriod() {
    return billingPeriod;
  }


  public void setBillingPeriod(APIBillingPeriodUsageOut billingPeriod) {
    this.billingPeriod = billingPeriod;
  }


  public APIPeriodUsageOut overageExclTax(Double overageExclTax) {
    
    this.overageExclTax = overageExclTax;
    return this;
  }

   /**
   * Overage amount including any tax.
   * @return overageExclTax
  **/
  @javax.annotation.Nullable
  public Double getOverageExclTax() {
    return overageExclTax;
  }


  public void setOverageExclTax(Double overageExclTax) {
    this.overageExclTax = overageExclTax;
  }


  public APIPeriodUsageOut overageInclTax(Double overageInclTax) {
    
    this.overageInclTax = overageInclTax;
    return this;
  }

   /**
   * Overage amount including tax (if applicable).
   * @return overageInclTax
  **/
  @javax.annotation.Nullable
  public Double getOverageInclTax() {
    return overageInclTax;
  }


  public void setOverageInclTax(Double overageInclTax) {
    this.overageInclTax = overageInclTax;
  }


  public APIPeriodUsageOut overageCurrency(String overageCurrency) {
    
    this.overageCurrency = overageCurrency;
    return this;
  }

   /**
   * Currency of the overage amount.
   * @return overageCurrency
  **/
  @javax.annotation.Nullable
  public String getOverageCurrency() {
    return overageCurrency;
  }


  public void setOverageCurrency(String overageCurrency) {
    this.overageCurrency = overageCurrency;
  }


  public APIPeriodUsageOut overageQuantity(Long overageQuantity) {
    
    this.overageQuantity = overageQuantity;
    return this;
  }

   /**
   * Quantity above monthly quota of the current subscritpion, in units.
   * @return overageQuantity
  **/
  @javax.annotation.Nullable
  public Long getOverageQuantity() {
    return overageQuantity;
  }


  public void setOverageQuantity(Long overageQuantity) {
    this.overageQuantity = overageQuantity;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIPeriodUsageOut apIPeriodUsageOut = (APIPeriodUsageOut) o;
    return Objects.equals(this.subscription, apIPeriodUsageOut.subscription) &&
        Objects.equals(this.billingPeriod, apIPeriodUsageOut.billingPeriod) &&
        Objects.equals(this.overageExclTax, apIPeriodUsageOut.overageExclTax) &&
        Objects.equals(this.overageInclTax, apIPeriodUsageOut.overageInclTax) &&
        Objects.equals(this.overageCurrency, apIPeriodUsageOut.overageCurrency) &&
        Objects.equals(this.overageQuantity, apIPeriodUsageOut.overageQuantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscription, billingPeriod, overageExclTax, overageInclTax, overageCurrency, overageQuantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIPeriodUsageOut {\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("    billingPeriod: ").append(toIndentedString(billingPeriod)).append("\n");
    sb.append("    overageExclTax: ").append(toIndentedString(overageExclTax)).append("\n");
    sb.append("    overageInclTax: ").append(toIndentedString(overageInclTax)).append("\n");
    sb.append("    overageCurrency: ").append(toIndentedString(overageCurrency)).append("\n");
    sb.append("    overageQuantity: ").append(toIndentedString(overageQuantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("subscription");
    openapiFields.add("billingPeriod");
    openapiFields.add("overageExclTax");
    openapiFields.add("overageInclTax");
    openapiFields.add("overageCurrency");
    openapiFields.add("overageQuantity");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to APIPeriodUsageOut
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!APIPeriodUsageOut.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in APIPeriodUsageOut is not found in the empty JSON string", APIPeriodUsageOut.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!APIPeriodUsageOut.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `APIPeriodUsageOut` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `subscription`
      if (jsonObj.get("subscription") != null && !jsonObj.get("subscription").isJsonNull()) {
        APIPlanSubscriptionOut.validateJsonObject(jsonObj.getAsJsonObject("subscription"));
      }
      // validate the optional field `billingPeriod`
      if (jsonObj.get("billingPeriod") != null && !jsonObj.get("billingPeriod").isJsonNull()) {
        APIBillingPeriodUsageOut.validateJsonObject(jsonObj.getAsJsonObject("billingPeriod"));
      }
      if ((jsonObj.get("overageCurrency") != null && !jsonObj.get("overageCurrency").isJsonNull()) && !jsonObj.get("overageCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `overageCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("overageCurrency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!APIPeriodUsageOut.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'APIPeriodUsageOut' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<APIPeriodUsageOut> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(APIPeriodUsageOut.class));

       return (TypeAdapter<T>) new TypeAdapter<APIPeriodUsageOut>() {
           @Override
           public void write(JsonWriter out, APIPeriodUsageOut value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public APIPeriodUsageOut read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of APIPeriodUsageOut given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of APIPeriodUsageOut
  * @throws IOException if the JSON string is invalid with respect to APIPeriodUsageOut
  */
  public static APIPeriodUsageOut fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, APIPeriodUsageOut.class);
  }

 /**
  * Convert an instance of APIPeriodUsageOut to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

