/*
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.namsor.sdk2.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.namsor.sdk2.invoke.JSON;

/**
 * CommunityEngageOptionOut
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-28T10:15:07.323+01:00[Europe/Berlin]")
public class CommunityEngageOptionOut {
  public static final String SERIALIZED_NAME_GENDER_FILTER = "genderFilter";
  @SerializedName(SERIALIZED_NAME_GENDER_FILTER)
  private List<String> genderFilter;

  public static final String SERIALIZED_NAME_ETHNICITY_FILTER = "ethnicityFilter";
  @SerializedName(SERIALIZED_NAME_ETHNICITY_FILTER)
  private List<String> ethnicityFilter;

  public static final String SERIALIZED_NAME_COUNTRY_OUT_FILTER = "countryOutFilter";
  @SerializedName(SERIALIZED_NAME_COUNTRY_OUT_FILTER)
  private List<String> countryOutFilter;

  public static final String SERIALIZED_NAME_US_RACE_ETHNICITY_FILTER = "usRaceEthnicityFilter";
  @SerializedName(SERIALIZED_NAME_US_RACE_ETHNICITY_FILTER)
  private List<String> usRaceEthnicityFilter;

  public CommunityEngageOptionOut() {
  }

  public CommunityEngageOptionOut genderFilter(List<String> genderFilter) {
    
    this.genderFilter = genderFilter;
    return this;
  }

  public CommunityEngageOptionOut addGenderFilterItem(String genderFilterItem) {
    if (this.genderFilter == null) {
      this.genderFilter = new ArrayList<>();
    }
    this.genderFilter.add(genderFilterItem);
    return this;
  }

   /**
   * The gender filter (null to allow all)
   * @return genderFilter
  **/
  @javax.annotation.Nullable
  public List<String> getGenderFilter() {
    return genderFilter;
  }


  public void setGenderFilter(List<String> genderFilter) {
    this.genderFilter = genderFilter;
  }


  public CommunityEngageOptionOut ethnicityFilter(List<String> ethnicityFilter) {
    
    this.ethnicityFilter = ethnicityFilter;
    return this;
  }

  public CommunityEngageOptionOut addEthnicityFilterItem(String ethnicityFilterItem) {
    if (this.ethnicityFilter == null) {
      this.ethnicityFilter = new ArrayList<>();
    }
    this.ethnicityFilter.add(ethnicityFilterItem);
    return this;
  }

   /**
   * The ethnicity filter (null to allow all)
   * @return ethnicityFilter
  **/
  @javax.annotation.Nullable
  public List<String> getEthnicityFilter() {
    return ethnicityFilter;
  }


  public void setEthnicityFilter(List<String> ethnicityFilter) {
    this.ethnicityFilter = ethnicityFilter;
  }


  public CommunityEngageOptionOut countryOutFilter(List<String> countryOutFilter) {
    
    this.countryOutFilter = countryOutFilter;
    return this;
  }

  public CommunityEngageOptionOut addCountryOutFilterItem(String countryOutFilterItem) {
    if (this.countryOutFilter == null) {
      this.countryOutFilter = new ArrayList<>();
    }
    this.countryOutFilter.add(countryOutFilterItem);
    return this;
  }

   /**
   * The output country filter (null to allow all)
   * @return countryOutFilter
  **/
  @javax.annotation.Nullable
  public List<String> getCountryOutFilter() {
    return countryOutFilter;
  }


  public void setCountryOutFilter(List<String> countryOutFilter) {
    this.countryOutFilter = countryOutFilter;
  }


  public CommunityEngageOptionOut usRaceEthnicityFilter(List<String> usRaceEthnicityFilter) {
    
    this.usRaceEthnicityFilter = usRaceEthnicityFilter;
    return this;
  }

  public CommunityEngageOptionOut addUsRaceEthnicityFilterItem(String usRaceEthnicityFilterItem) {
    if (this.usRaceEthnicityFilter == null) {
      this.usRaceEthnicityFilter = new ArrayList<>();
    }
    this.usRaceEthnicityFilter.add(usRaceEthnicityFilterItem);
    return this;
  }

   /**
   * The output US race/ethnicity filter (null to allow all)
   * @return usRaceEthnicityFilter
  **/
  @javax.annotation.Nullable
  public List<String> getUsRaceEthnicityFilter() {
    return usRaceEthnicityFilter;
  }


  public void setUsRaceEthnicityFilter(List<String> usRaceEthnicityFilter) {
    this.usRaceEthnicityFilter = usRaceEthnicityFilter;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunityEngageOptionOut communityEngageOptionOut = (CommunityEngageOptionOut) o;
    return Objects.equals(this.genderFilter, communityEngageOptionOut.genderFilter) &&
        Objects.equals(this.ethnicityFilter, communityEngageOptionOut.ethnicityFilter) &&
        Objects.equals(this.countryOutFilter, communityEngageOptionOut.countryOutFilter) &&
        Objects.equals(this.usRaceEthnicityFilter, communityEngageOptionOut.usRaceEthnicityFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(genderFilter, ethnicityFilter, countryOutFilter, usRaceEthnicityFilter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunityEngageOptionOut {\n");
    sb.append("    genderFilter: ").append(toIndentedString(genderFilter)).append("\n");
    sb.append("    ethnicityFilter: ").append(toIndentedString(ethnicityFilter)).append("\n");
    sb.append("    countryOutFilter: ").append(toIndentedString(countryOutFilter)).append("\n");
    sb.append("    usRaceEthnicityFilter: ").append(toIndentedString(usRaceEthnicityFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("genderFilter");
    openapiFields.add("ethnicityFilter");
    openapiFields.add("countryOutFilter");
    openapiFields.add("usRaceEthnicityFilter");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CommunityEngageOptionOut
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CommunityEngageOptionOut.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CommunityEngageOptionOut is not found in the empty JSON string", CommunityEngageOptionOut.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CommunityEngageOptionOut.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CommunityEngageOptionOut` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("genderFilter") != null && !jsonObj.get("genderFilter").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `genderFilter` to be an array in the JSON string but got `%s`", jsonObj.get("genderFilter").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("ethnicityFilter") != null && !jsonObj.get("ethnicityFilter").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `ethnicityFilter` to be an array in the JSON string but got `%s`", jsonObj.get("ethnicityFilter").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("countryOutFilter") != null && !jsonObj.get("countryOutFilter").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryOutFilter` to be an array in the JSON string but got `%s`", jsonObj.get("countryOutFilter").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("usRaceEthnicityFilter") != null && !jsonObj.get("usRaceEthnicityFilter").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `usRaceEthnicityFilter` to be an array in the JSON string but got `%s`", jsonObj.get("usRaceEthnicityFilter").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommunityEngageOptionOut.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommunityEngageOptionOut' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommunityEngageOptionOut> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommunityEngageOptionOut.class));

       return (TypeAdapter<T>) new TypeAdapter<CommunityEngageOptionOut>() {
           @Override
           public void write(JsonWriter out, CommunityEngageOptionOut value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommunityEngageOptionOut read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CommunityEngageOptionOut given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CommunityEngageOptionOut
  * @throws IOException if the JSON string is invalid with respect to CommunityEngageOptionOut
  */
  public static CommunityEngageOptionOut fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommunityEngageOptionOut.class);
  }

 /**
  * Convert an instance of CommunityEngageOptionOut to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

