/*
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.26
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.namsor.sdk2.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents the geographic name origin at a country subclassification level (usually regional or state level).
 */
@ApiModel(description = "Represents the geographic name origin at a country subclassification level (usually regional or state level).")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-19T10:33:14.621+02:00[Europe/Berlin]")
public class FirstLastNameGeoSubclassificationOut {
  public static final String SERIALIZED_NAME_SCRIPT = "script";
  @SerializedName(SERIALIZED_NAME_SCRIPT)
  private String script;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_EXPLANATION = "explanation";
  @SerializedName(SERIALIZED_NAME_EXPLANATION)
  private String explanation;

  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_COUNTRY_ISO2 = "countryIso2";
  @SerializedName(SERIALIZED_NAME_COUNTRY_ISO2)
  private String countryIso2;

  public static final String SERIALIZED_NAME_SUB_CLASSIFICATION = "subClassification";
  @SerializedName(SERIALIZED_NAME_SUB_CLASSIFICATION)
  private String subClassification;

  public static final String SERIALIZED_NAME_SUB_CLASSIFICATION_ALT = "subClassificationAlt";
  @SerializedName(SERIALIZED_NAME_SUB_CLASSIFICATION_ALT)
  private String subClassificationAlt;

  public static final String SERIALIZED_NAME_SUBCLASSIFICATION_TOP = "subclassificationTop";
  @SerializedName(SERIALIZED_NAME_SUBCLASSIFICATION_TOP)
  private List<String> subclassificationTop = new ArrayList<String>();

  public static final String SERIALIZED_NAME_SCORE = "score";
  @SerializedName(SERIALIZED_NAME_SCORE)
  private Double score;

  public static final String SERIALIZED_NAME_PROBABILITY_CALIBRATED = "probabilityCalibrated";
  @SerializedName(SERIALIZED_NAME_PROBABILITY_CALIBRATED)
  private Double probabilityCalibrated;

  public static final String SERIALIZED_NAME_PROBABILITY_ALT_CALIBRATED = "probabilityAltCalibrated";
  @SerializedName(SERIALIZED_NAME_PROBABILITY_ALT_CALIBRATED)
  private Double probabilityAltCalibrated;

  public FirstLastNameGeoSubclassificationOut script(String script) {
    this.script = script;
    return this;
  }

   /**
   * Get script
   * @return script
  **/
  @ApiModelProperty(value = "")
  public String getScript() {
    return script;
  }

  public void setScript(String script) {
    this.script = script;
  }

  public FirstLastNameGeoSubclassificationOut id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FirstLastNameGeoSubclassificationOut explanation(String explanation) {
    this.explanation = explanation;
    return this;
  }

   /**
   * Get explanation
   * @return explanation
  **/
  @ApiModelProperty(value = "")
  public String getExplanation() {
    return explanation;
  }

  public void setExplanation(String explanation) {
    this.explanation = explanation;
  }

  public FirstLastNameGeoSubclassificationOut firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * The first name (also known as given name)
   * @return firstName
  **/
  @ApiModelProperty(value = "The first name (also known as given name)")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public FirstLastNameGeoSubclassificationOut lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * The last name (also known as family name, or surname)
   * @return lastName
  **/
  @ApiModelProperty(value = "The last name (also known as family name, or surname)")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public FirstLastNameGeoSubclassificationOut countryIso2(String countryIso2) {
    this.countryIso2 = countryIso2;
    return this;
  }

   /**
   * The input country ISO2 code
   * @return countryIso2
  **/
  @ApiModelProperty(value = "The input country ISO2 code")
  public String getCountryIso2() {
    return countryIso2;
  }

  public void setCountryIso2(String countryIso2) {
    this.countryIso2 = countryIso2;
  }

  public FirstLastNameGeoSubclassificationOut subClassification(String subClassification) {
    this.subClassification = subClassification;
    return this;
  }

   /**
   * Most likely subclassification ISO_3166-2 code
   * @return subClassification
  **/
  @ApiModelProperty(value = "Most likely subclassification ISO_3166-2 code")
  public String getSubClassification() {
    return subClassification;
  }

  public void setSubClassification(String subClassification) {
    this.subClassification = subClassification;
  }

  public FirstLastNameGeoSubclassificationOut subClassificationAlt(String subClassificationAlt) {
    this.subClassificationAlt = subClassificationAlt;
    return this;
  }

   /**
   * Second best alternative : subclassification ISO_3166-2 code
   * @return subClassificationAlt
  **/
  @ApiModelProperty(value = "Second best alternative : subclassification ISO_3166-2 code")
  public String getSubClassificationAlt() {
    return subClassificationAlt;
  }

  public void setSubClassificationAlt(String subClassificationAlt) {
    this.subClassificationAlt = subClassificationAlt;
  }

  public FirstLastNameGeoSubclassificationOut subclassificationTop(List<String> subclassificationTop) {
    this.subclassificationTop = subclassificationTop;
    return this;
  }

  public FirstLastNameGeoSubclassificationOut addSubclassificationTopItem(String subclassificationTopItem) {
    if (this.subclassificationTop == null) {
      this.subclassificationTop = new ArrayList<String>();
    }
    this.subclassificationTop.add(subclassificationTopItem);
    return this;
  }

   /**
   * List subclassification ISO_3166-2 codes (top 10)
   * @return subclassificationTop
  **/
  @ApiModelProperty(value = "List subclassification ISO_3166-2 codes (top 10)")
  public List<String> getSubclassificationTop() {
    return subclassificationTop;
  }

  public void setSubclassificationTop(List<String> subclassificationTop) {
    this.subclassificationTop = subclassificationTop;
  }

  public FirstLastNameGeoSubclassificationOut score(Double score) {
    this.score = score;
    return this;
  }

   /**
   * Compatibility to NamSor_v1 Origin score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. 
   * minimum: 0
   * maximum: 100
   * @return score
  **/
  @ApiModelProperty(value = "Compatibility to NamSor_v1 Origin score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. ")
  public Double getScore() {
    return score;
  }

  public void setScore(Double score) {
    this.score = score;
  }

  public FirstLastNameGeoSubclassificationOut probabilityCalibrated(Double probabilityCalibrated) {
    this.probabilityCalibrated = probabilityCalibrated;
    return this;
  }

   /**
   * The calibrated probability for subclassification to have been guessed correctly. -1 &#x3D; still calibrating. 
   * minimum: -1
   * maximum: 1
   * @return probabilityCalibrated
  **/
  @ApiModelProperty(value = "The calibrated probability for subclassification to have been guessed correctly. -1 = still calibrating. ")
  public Double getProbabilityCalibrated() {
    return probabilityCalibrated;
  }

  public void setProbabilityCalibrated(Double probabilityCalibrated) {
    this.probabilityCalibrated = probabilityCalibrated;
  }

  public FirstLastNameGeoSubclassificationOut probabilityAltCalibrated(Double probabilityAltCalibrated) {
    this.probabilityAltCalibrated = probabilityAltCalibrated;
    return this;
  }

   /**
   * The calibrated probability for subclassification OR subclassificationAlt to have been guessed correctly. -1 &#x3D; still calibrating. 
   * minimum: -1
   * maximum: 1
   * @return probabilityAltCalibrated
  **/
  @ApiModelProperty(value = "The calibrated probability for subclassification OR subclassificationAlt to have been guessed correctly. -1 = still calibrating. ")
  public Double getProbabilityAltCalibrated() {
    return probabilityAltCalibrated;
  }

  public void setProbabilityAltCalibrated(Double probabilityAltCalibrated) {
    this.probabilityAltCalibrated = probabilityAltCalibrated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FirstLastNameGeoSubclassificationOut firstLastNameGeoSubclassificationOut = (FirstLastNameGeoSubclassificationOut) o;
    return Objects.equals(this.script, firstLastNameGeoSubclassificationOut.script) &&
        Objects.equals(this.id, firstLastNameGeoSubclassificationOut.id) &&
        Objects.equals(this.explanation, firstLastNameGeoSubclassificationOut.explanation) &&
        Objects.equals(this.firstName, firstLastNameGeoSubclassificationOut.firstName) &&
        Objects.equals(this.lastName, firstLastNameGeoSubclassificationOut.lastName) &&
        Objects.equals(this.countryIso2, firstLastNameGeoSubclassificationOut.countryIso2) &&
        Objects.equals(this.subClassification, firstLastNameGeoSubclassificationOut.subClassification) &&
        Objects.equals(this.subClassificationAlt, firstLastNameGeoSubclassificationOut.subClassificationAlt) &&
        Objects.equals(this.subclassificationTop, firstLastNameGeoSubclassificationOut.subclassificationTop) &&
        Objects.equals(this.score, firstLastNameGeoSubclassificationOut.score) &&
        Objects.equals(this.probabilityCalibrated, firstLastNameGeoSubclassificationOut.probabilityCalibrated) &&
        Objects.equals(this.probabilityAltCalibrated, firstLastNameGeoSubclassificationOut.probabilityAltCalibrated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(script, id, explanation, firstName, lastName, countryIso2, subClassification, subClassificationAlt, subclassificationTop, score, probabilityCalibrated, probabilityAltCalibrated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FirstLastNameGeoSubclassificationOut {\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    explanation: ").append(toIndentedString(explanation)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    countryIso2: ").append(toIndentedString(countryIso2)).append("\n");
    sb.append("    subClassification: ").append(toIndentedString(subClassification)).append("\n");
    sb.append("    subClassificationAlt: ").append(toIndentedString(subClassificationAlt)).append("\n");
    sb.append("    subclassificationTop: ").append(toIndentedString(subclassificationTop)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    probabilityCalibrated: ").append(toIndentedString(probabilityCalibrated)).append("\n");
    sb.append("    probabilityAltCalibrated: ").append(toIndentedString(probabilityAltCalibrated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

