/*
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.30
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.namsor.sdk2.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * List of countries and regions
 */
@ApiModel(description = "List of countries and regions")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-11T10:56:47.519625+02:00[Europe/Berlin]")
public class RegionISO {
  public static final String SERIALIZED_NAME_COUNTRY_NAME = "countryName";
  @SerializedName(SERIALIZED_NAME_COUNTRY_NAME)
  private String countryName;

  public static final String SERIALIZED_NAME_COUNTRY_NUM_CODE = "countryNumCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_NUM_CODE)
  private String countryNumCode;

  public static final String SERIALIZED_NAME_COUNTRY_I_S_O2 = "countryISO2";
  @SerializedName(SERIALIZED_NAME_COUNTRY_I_S_O2)
  private String countryISO2;

  public static final String SERIALIZED_NAME_COUNTRY_I_S_O3 = "countryISO3";
  @SerializedName(SERIALIZED_NAME_COUNTRY_I_S_O3)
  private String countryISO3;

  public static final String SERIALIZED_NAME_COUNTRY_F_I_P_S = "countryFIPS";
  @SerializedName(SERIALIZED_NAME_COUNTRY_F_I_P_S)
  private String countryFIPS;

  public static final String SERIALIZED_NAME_SUBREGION = "subregion";
  @SerializedName(SERIALIZED_NAME_SUBREGION)
  private String subregion;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private String region;

  public static final String SERIALIZED_NAME_TOPREGION = "topregion";
  @SerializedName(SERIALIZED_NAME_TOPREGION)
  private String topregion;

  public RegionISO countryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

   /**
   * Get countryName
   * @return countryName
  **/
  @ApiModelProperty(value = "")
  public String getCountryName() {
    return countryName;
  }

  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  public RegionISO countryNumCode(String countryNumCode) {
    this.countryNumCode = countryNumCode;
    return this;
  }

   /**
   * Get countryNumCode
   * @return countryNumCode
  **/
  @ApiModelProperty(value = "")
  public String getCountryNumCode() {
    return countryNumCode;
  }

  public void setCountryNumCode(String countryNumCode) {
    this.countryNumCode = countryNumCode;
  }

  public RegionISO countryISO2(String countryISO2) {
    this.countryISO2 = countryISO2;
    return this;
  }

   /**
   * Get countryISO2
   * @return countryISO2
  **/
  @ApiModelProperty(value = "")
  public String getCountryISO2() {
    return countryISO2;
  }

  public void setCountryISO2(String countryISO2) {
    this.countryISO2 = countryISO2;
  }

  public RegionISO countryISO3(String countryISO3) {
    this.countryISO3 = countryISO3;
    return this;
  }

   /**
   * Get countryISO3
   * @return countryISO3
  **/
  @ApiModelProperty(value = "")
  public String getCountryISO3() {
    return countryISO3;
  }

  public void setCountryISO3(String countryISO3) {
    this.countryISO3 = countryISO3;
  }

  public RegionISO countryFIPS(String countryFIPS) {
    this.countryFIPS = countryFIPS;
    return this;
  }

   /**
   * Get countryFIPS
   * @return countryFIPS
  **/
  @ApiModelProperty(value = "")
  public String getCountryFIPS() {
    return countryFIPS;
  }

  public void setCountryFIPS(String countryFIPS) {
    this.countryFIPS = countryFIPS;
  }

  public RegionISO subregion(String subregion) {
    this.subregion = subregion;
    return this;
  }

   /**
   * Get subregion
   * @return subregion
  **/
  @ApiModelProperty(value = "")
  public String getSubregion() {
    return subregion;
  }

  public void setSubregion(String subregion) {
    this.subregion = subregion;
  }

  public RegionISO region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @ApiModelProperty(value = "")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public RegionISO topregion(String topregion) {
    this.topregion = topregion;
    return this;
  }

   /**
   * Get topregion
   * @return topregion
  **/
  @ApiModelProperty(value = "")
  public String getTopregion() {
    return topregion;
  }

  public void setTopregion(String topregion) {
    this.topregion = topregion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionISO regionISO = (RegionISO) o;
    return Objects.equals(this.countryName, regionISO.countryName) &&
        Objects.equals(this.countryNumCode, regionISO.countryNumCode) &&
        Objects.equals(this.countryISO2, regionISO.countryISO2) &&
        Objects.equals(this.countryISO3, regionISO.countryISO3) &&
        Objects.equals(this.countryFIPS, regionISO.countryFIPS) &&
        Objects.equals(this.subregion, regionISO.subregion) &&
        Objects.equals(this.region, regionISO.region) &&
        Objects.equals(this.topregion, regionISO.topregion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryName, countryNumCode, countryISO2, countryISO3, countryFIPS, subregion, region, topregion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionISO {\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    countryNumCode: ").append(toIndentedString(countryNumCode)).append("\n");
    sb.append("    countryISO2: ").append(toIndentedString(countryISO2)).append("\n");
    sb.append("    countryISO3: ").append(toIndentedString(countryISO3)).append("\n");
    sb.append("    countryFIPS: ").append(toIndentedString(countryFIPS)).append("\n");
    sb.append("    subregion: ").append(toIndentedString(subregion)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    topregion: ").append(toIndentedString(topregion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

