/*
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 1000 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.2-beta
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.namsor.sdk2.api;

import com.namsor.sdk2.invoke.ApiException;
import com.namsor.sdk2.model.BatchFirstLastNameDiasporaedOut;
import com.namsor.sdk2.model.BatchFirstLastNameGenderedOut;
import com.namsor.sdk2.model.BatchFirstLastNameGeoIn;
import com.namsor.sdk2.model.BatchFirstLastNameGeoZippedIn;
import com.namsor.sdk2.model.BatchFirstLastNameIn;
import com.namsor.sdk2.model.BatchFirstLastNameOriginedOut;
import com.namsor.sdk2.model.BatchFirstLastNameUSRaceEthnicityOut;
import com.namsor.sdk2.model.BatchParsedFullNameGeoIn;
import com.namsor.sdk2.model.BatchParsedFullNameIn;
import com.namsor.sdk2.model.BatchPersonalNameGeoOut;
import com.namsor.sdk2.model.BatchPersonalNameIn;
import com.namsor.sdk2.model.FirstLastNameDiasporaedOut;
import com.namsor.sdk2.model.FirstLastNameGenderedOut;
import com.namsor.sdk2.model.FirstLastNameOriginedOut;
import com.namsor.sdk2.model.FirstLastNameUSRaceEthnicityOut;
import com.namsor.sdk2.model.PersonalNameGeoOut;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PersonalApi
 */
@Ignore
public class PersonalApiTest {

    private final PersonalApi api = new PersonalApi();

    
    /**
     * [USES 10 UNITS] Infer the likely country of residence of a personal full name, or one surname. Assumes names as they are in the country of residence OR the country of origin.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void countryTest() throws ApiException {
        String personalNameFull = null;
        PersonalNameGeoOut response = api.country(personalNameFull);

        // TODO: test validations
    }
    
    /**
     * [USES 10 UNITS] Infer the likely country of residence of up to 1000 personal full names, or surnames. Assumes names as they are in the country of residence OR the country of origin.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void countryBatchTest() throws ApiException {
        BatchPersonalNameIn batchPersonalNameIn = null;
        BatchPersonalNameGeoOut response = api.countryBatch(batchPersonalNameIn);

        // TODO: test validations
    }
    
    /**
     * [USES 20 UNITS] Infer the likely ethnicity/diaspora of a personal name, given a country of residence ISO2 code (ex. US, CA, AU, NZ etc.)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void diasporaTest() throws ApiException {
        String countryIso2 = null;
        String firstName = null;
        String lastName = null;
        FirstLastNameDiasporaedOut response = api.diaspora(countryIso2, firstName, lastName);

        // TODO: test validations
    }
    
    /**
     * [USES 20 UNITS] Infer the likely ethnicity/diaspora of up to 1000 personal names, given a country of residence ISO2 code (ex. US, CA, AU, NZ etc.)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void diasporaBatchTest() throws ApiException {
        BatchFirstLastNameGeoIn batchFirstLastNameGeoIn = null;
        BatchFirstLastNameDiasporaedOut response = api.diasporaBatch(batchFirstLastNameGeoIn);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of a name.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genderTest() throws ApiException {
        String firstName = null;
        String lastName = null;
        FirstLastNameGenderedOut response = api.gender(firstName, lastName);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of up to 1000 names, detecting automatically the cultural context.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genderBatchTest() throws ApiException {
        BatchFirstLastNameIn batchFirstLastNameIn = null;
        BatchFirstLastNameGenderedOut response = api.genderBatch(batchFirstLastNameIn);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of a full name, ex. John H. Smith
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genderFullTest() throws ApiException {
        String fullName = null;
        FirstLastNameGenderedOut response = api.genderFull(fullName);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of up to 1000 full names, detecting automatically the cultural context.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genderFullBatchTest() throws ApiException {
        BatchPersonalNameIn batchPersonalNameIn = null;
        BatchFirstLastNameGenderedOut response = api.genderFullBatch(batchPersonalNameIn);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of a full name, given a local context (ISO2 country code).
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genderFullGeoTest() throws ApiException {
        String fullName = null;
        String countryIso2 = null;
        FirstLastNameGenderedOut response = api.genderFullGeo(fullName, countryIso2);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of up to 1000 full names, with a given cultural context (country ISO2 code).
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genderFullGeoBatchTest() throws ApiException {
        BatchPersonalNameIn batchPersonalNameIn = null;
        BatchFirstLastNameGenderedOut response = api.genderFullGeoBatch(batchPersonalNameIn);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of a name, given a local context (ISO2 country code).
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genderGeoTest() throws ApiException {
        String firstName = null;
        String lastName = null;
        String countryIso2 = null;
        FirstLastNameGenderedOut response = api.genderGeo(firstName, lastName, countryIso2);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of up to 1000 names, each given a local context (ISO2 country code).
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genderGeoBatchTest() throws ApiException {
        BatchFirstLastNameGeoIn batchFirstLastNameGeoIn = null;
        BatchFirstLastNameGenderedOut response = api.genderGeoBatch(batchFirstLastNameGeoIn);

        // TODO: test validations
    }
    
    /**
     * [USES 10 UNITS] Infer the likely country of origin of a personal name. Assumes names as they are in the country of origin. For US, CA, AU, NZ and other melting-pots : use &#39;diaspora&#39; instead.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void originTest() throws ApiException {
        String firstName = null;
        String lastName = null;
        FirstLastNameOriginedOut response = api.origin(firstName, lastName);

        // TODO: test validations
    }
    
    /**
     * [USES 10 UNITS] Infer the likely country of origin of up to 1000 names, detecting automatically the cultural context.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void originBatchTest() throws ApiException {
        BatchFirstLastNameIn batchFirstLastNameIn = null;
        BatchFirstLastNameOriginedOut response = api.originBatch(batchFirstLastNameIn);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of up to 1000 fully parsed names, detecting automatically the cultural context.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void parsedGenderBatchTest() throws ApiException {
        BatchParsedFullNameIn batchParsedFullNameIn = null;
        BatchFirstLastNameGenderedOut response = api.parsedGenderBatch(batchParsedFullNameIn);

        // TODO: test validations
    }
    
    /**
     * Infer the likely gender of up to 1000 fully parsed names, detecting automatically the cultural context.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void parsedGenderGeoBatchTest() throws ApiException {
        BatchParsedFullNameGeoIn batchParsedFullNameGeoIn = null;
        BatchFirstLastNameGenderedOut response = api.parsedGenderGeoBatch(batchParsedFullNameGeoIn);

        // TODO: test validations
    }
    
    /**
     * [USES 10 UNITS] Infer a US resident&#39;s likely race/ethnicity according to US Census taxonomy.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usRaceEthnicityTest() throws ApiException {
        String firstName = null;
        String lastName = null;
        FirstLastNameUSRaceEthnicityOut response = api.usRaceEthnicity(firstName, lastName);

        // TODO: test validations
    }
    
    /**
     * [USES 10 UNITS] Infer up-to 1000 US resident&#39;s likely race/ethnicity according to US Census taxonomy.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usRaceEthnicityBatchTest() throws ApiException {
        BatchFirstLastNameGeoIn batchFirstLastNameGeoIn = null;
        BatchFirstLastNameUSRaceEthnicityOut response = api.usRaceEthnicityBatch(batchFirstLastNameGeoIn);

        // TODO: test validations
    }
    
    /**
     * [USES 10 UNITS] Infer a US resident&#39;s likely race/ethnicity according to US Census taxonomy, using (optional) ZIP5 code info.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usRaceEthnicityZIP5Test() throws ApiException {
        String firstName = null;
        String lastName = null;
        String zip5Code = null;
        FirstLastNameUSRaceEthnicityOut response = api.usRaceEthnicityZIP5(firstName, lastName, zip5Code);

        // TODO: test validations
    }
    
    /**
     * [USES 10 UNITS] Infer up-to 1000 US resident&#39;s likely race/ethnicity according to US Census taxonomy, with (optional) ZIP code.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usZipRaceEthnicityBatchTest() throws ApiException {
        BatchFirstLastNameGeoZippedIn batchFirstLastNameGeoZippedIn = null;
        BatchFirstLastNameUSRaceEthnicityOut response = api.usZipRaceEthnicityBatch(batchFirstLastNameGeoZippedIn);

        // TODO: test validations
    }
    
}
