/*
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.10
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.namsor.sdk2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for APIClassifierOut
 */
public class APIClassifierOutTest {
    private final APIClassifierOut model = new APIClassifierOut();

    /**
     * Model tests for APIClassifierOut
     */
    @Test
    public void testAPIClassifierOut() {
        // TODO: test APIClassifierOut
    }

    /**
     * Test the property 'classifierName'
     */
    @Test
    public void classifierNameTest() {
        // TODO: test classifierName
    }

    /**
     * Test the property 'serving'
     */
    @Test
    public void servingTest() {
        // TODO: test serving
    }

    /**
     * Test the property 'learning'
     */
    @Test
    public void learningTest() {
        // TODO: test learning
    }

    /**
     * Test the property 'shuttingDown'
     */
    @Test
    public void shuttingDownTest() {
        // TODO: test shuttingDown
    }

    /**
     * Test the property 'probabilityCalibrated'
     */
    @Test
    public void probabilityCalibratedTest() {
        // TODO: test probabilityCalibrated
    }

}
