/*
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.12
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.namsor.sdk2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BillingInfoInOut
 */
public class BillingInfoInOutTest {
    private final BillingInfoInOut model = new BillingInfoInOut();

    /**
     * Model tests for BillingInfoInOut
     */
    @Test
    public void testBillingInfoInOut() {
        // TODO: test BillingInfoInOut
    }

    /**
     * Test the property 'billingEmail'
     */
    @Test
    public void billingEmailTest() {
        // TODO: test billingEmail
    }

    /**
     * Test the property 'preferredCurrency'
     */
    @Test
    public void preferredCurrencyTest() {
        // TODO: test preferredCurrency
    }

    /**
     * Test the property 'customerName'
     */
    @Test
    public void customerNameTest() {
        // TODO: test customerName
    }

    /**
     * Test the property 'customerPhone'
     */
    @Test
    public void customerPhoneTest() {
        // TODO: test customerPhone
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'addressCity'
     */
    @Test
    public void addressCityTest() {
        // TODO: test addressCity
    }

    /**
     * Test the property 'addressPostalCode'
     */
    @Test
    public void addressPostalCodeTest() {
        // TODO: test addressPostalCode
    }

    /**
     * Test the property 'addressState'
     */
    @Test
    public void addressStateTest() {
        // TODO: test addressState
    }

    /**
     * Test the property 'addressCountry'
     */
    @Test
    public void addressCountryTest() {
        // TODO: test addressCountry
    }

    /**
     * Test the property 'vatID'
     */
    @Test
    public void vatIDTest() {
        // TODO: test vatID
    }

}
