/*
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.11
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.namsor.sdk2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FirstLastNameOriginedOut
 */
public class FirstLastNameOriginedOutTest {
    private final FirstLastNameOriginedOut model = new FirstLastNameOriginedOut();

    /**
     * Model tests for FirstLastNameOriginedOut
     */
    @Test
    public void testFirstLastNameOriginedOut() {
        // TODO: test FirstLastNameOriginedOut
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'countryOrigin'
     */
    @Test
    public void countryOriginTest() {
        // TODO: test countryOrigin
    }

    /**
     * Test the property 'countryOriginAlt'
     */
    @Test
    public void countryOriginAltTest() {
        // TODO: test countryOriginAlt
    }

    /**
     * Test the property 'countriesOriginTop'
     */
    @Test
    public void countriesOriginTopTest() {
        // TODO: test countriesOriginTop
    }

    /**
     * Test the property 'score'
     */
    @Test
    public void scoreTest() {
        // TODO: test score
    }

    /**
     * Test the property 'regionOrigin'
     */
    @Test
    public void regionOriginTest() {
        // TODO: test regionOrigin
    }

    /**
     * Test the property 'topRegionOrigin'
     */
    @Test
    public void topRegionOriginTest() {
        // TODO: test topRegionOrigin
    }

    /**
     * Test the property 'subRegionOrigin'
     */
    @Test
    public void subRegionOriginTest() {
        // TODO: test subRegionOrigin
    }

    /**
     * Test the property 'probabilityCalibrated'
     */
    @Test
    public void probabilityCalibratedTest() {
        // TODO: test probabilityCalibrated
    }

    /**
     * Test the property 'probabilityAltCalibrated'
     */
    @Test
    public void probabilityAltCalibratedTest() {
        // TODO: test probabilityAltCalibrated
    }

}
