/*
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.6
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.namsor.sdk2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InvoiceItemOut
 */
public class InvoiceItemOutTest {
    private final InvoiceItemOut model = new InvoiceItemOut();

    /**
     * Model tests for InvoiceItemOut
     */
    @Test
    public void testInvoiceItemOut() {
        // TODO: test InvoiceItemOut
    }

    /**
     * Test the property 'itemId'
     */
    @Test
    public void itemIdTest() {
        // TODO: test itemId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'subscription'
     */
    @Test
    public void subscriptionTest() {
        // TODO: test subscription
    }

    /**
     * Test the property 'subscriptionItem'
     */
    @Test
    public void subscriptionItemTest() {
        // TODO: test subscriptionItem
    }

    /**
     * Test the property 'invoiceItemType'
     */
    @Test
    public void invoiceItemTypeTest() {
        // TODO: test invoiceItemType
    }

    /**
     * Test the property 'planNickname'
     */
    @Test
    public void planNicknameTest() {
        // TODO: test planNickname
    }

    /**
     * Test the property 'planDesc'
     */
    @Test
    public void planDescTest() {
        // TODO: test planDesc
    }

    /**
     * Test the property 'planName'
     */
    @Test
    public void planNameTest() {
        // TODO: test planName
    }

}
